# This workflow will build a package using Maven and then publish it to GitHub packages when a release is created

name: Publish package to GitHub Packages

on:
  workflow_dispatch

jobs:

  build:
    name: Build
    runs-on: ubuntu-20.04    
    steps:
    - name: Checking out
      uses: actions/checkout@v3
      with:        
        fetch-depth: 0 # Disabling shallow clone is recommended for improving relevancy of reporting
    - name: Set up JDK 11
      uses: actions/setup-java@v3
      with:
        java-version: '11'
        distribution: 'temurin'
        server-id: github # Value of the distributionManagement/repository/id field of the pom.xml
        settings-path: ${{ github.workspace }} # location for the settings.xml file
    - name: Build with Maven
      run: mvn -B -ntp clean install --file pom.xml -DskipTests      
    - name: Upload artifact for deployment job
      uses: actions/upload-artifact@v2
      with:
        name: java-app
        path: '${{ github.workspace }}/target/*.jar'	

  publish:
    runs-on: ubuntu-20.04
    needs: build
    permissions:
      contents: read
      packages: write
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-java@v3
        with:
          java-version: '11'
          distribution: 'adopt'
      - name: Publish package
        run: mvn --batch-mode deploy
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}