name: Publish Project

on:  
  workflow_dispatch:

jobs:
  build:
    name: Build
    runs-on: ubuntu-20.04

    steps:
      - name: Checking out
        uses: actions/checkout@v3
        with:
          fetch-depth: 1

      - name: Set up JDK 11
        uses: actions/setup-java@v3
        with:
          java-version: "11"
          distribution: "temurin"
          cache: maven

      - name: Cache all the things
        uses: actions/cache@v2
        with:
          path: ~/.m2
          key: ${{ runner.os }}-m2-${{ hashFiles('**/pom.xml') }}
          restore-keys: ${{ runner.os }}-m2

      - name: Extract project name
        id: project-name
        uses: actions/github-script@v3
        with:
          script: return context.repo.repo
          result-encoding: string          

      - name: Build ${{ steps.project-name.outputs.result }}
        id: maven-build
        run: |
          mvn -B clean install

          # Maven shade keeps the unshaded JAR under target/original-vvv.jar
          # We don't want to put this unshaded JAR in the release because it wouldn't
          # work on a server.
          JAR_PATH=$(ls ./target/*.jar | grep -vE "^./[^/]+/original-" | tail -n 1)
          JAR_NAME=$(basename $JAR_PATH)

          echo "jar_path=$JAR_PATH" >> $GITHUB_ENV
          echo "jar_name=$JAR_NAME" >> $GITHUB_ENV

        env:
          GIT_REF_NAME: ${{ github.ref }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Create new GitHub Release
        id: create-release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ github.ref }}
          release_name: Release ${{ github.ref }}
          draft: true
          prerelease: false

      - name: Add ${{ steps.project-name.outputs.result }} JAR to GitHub Release
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create-release.outputs.upload_url }}
          asset_path: ${{ env.jar_path }}
          asset_name: ${{ env.jar_name }}
          asset_content_type: application/java-archive